name: Auto Commit Bot

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "abdulsamadmughal1020@gmail.com"

      - name: Make a fake commit
        run: |
          date >> commit.log
          git add commit.log
          git commit -m "Automated commit: $(date)" || echo "No changes to commit"
          git push
